require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NovinkiesController do

  # This should return the minimal set of attributes required to create a valid
  # Novinky. As you add validations to Novinky, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NovinkiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all novinkies as @novinkies" do
      novinky = Novinky.create! valid_attributes
      get :index, {}, valid_session
      assigns(:novinkies).should eq([novinky])
    end
  end

  describe "GET show" do
    it "assigns the requested novinky as @novinky" do
      novinky = Novinky.create! valid_attributes
      get :show, {:id => novinky.to_param}, valid_session
      assigns(:novinky).should eq(novinky)
    end
  end

  describe "GET new" do
    it "assigns a new novinky as @novinky" do
      get :new, {}, valid_session
      assigns(:novinky).should be_a_new(Novinky)
    end
  end

  describe "GET edit" do
    it "assigns the requested novinky as @novinky" do
      novinky = Novinky.create! valid_attributes
      get :edit, {:id => novinky.to_param}, valid_session
      assigns(:novinky).should eq(novinky)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Novinky" do
        expect {
          post :create, {:novinky => valid_attributes}, valid_session
        }.to change(Novinky, :count).by(1)
      end

      it "assigns a newly created novinky as @novinky" do
        post :create, {:novinky => valid_attributes}, valid_session
        assigns(:novinky).should be_a(Novinky)
        assigns(:novinky).should be_persisted
      end

      it "redirects to the created novinky" do
        post :create, {:novinky => valid_attributes}, valid_session
        response.should redirect_to(Novinky.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved novinky as @novinky" do
        # Trigger the behavior that occurs when invalid params are submitted
        Novinky.any_instance.stub(:save).and_return(false)
        post :create, {:novinky => { "title" => "invalid value" }}, valid_session
        assigns(:novinky).should be_a_new(Novinky)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Novinky.any_instance.stub(:save).and_return(false)
        post :create, {:novinky => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested novinky" do
        novinky = Novinky.create! valid_attributes
        # Assuming there are no other novinkies in the database, this
        # specifies that the Novinky created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Novinky.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => novinky.to_param, :novinky => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested novinky as @novinky" do
        novinky = Novinky.create! valid_attributes
        put :update, {:id => novinky.to_param, :novinky => valid_attributes}, valid_session
        assigns(:novinky).should eq(novinky)
      end

      it "redirects to the novinky" do
        novinky = Novinky.create! valid_attributes
        put :update, {:id => novinky.to_param, :novinky => valid_attributes}, valid_session
        response.should redirect_to(novinky)
      end
    end

    describe "with invalid params" do
      it "assigns the novinky as @novinky" do
        novinky = Novinky.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Novinky.any_instance.stub(:save).and_return(false)
        put :update, {:id => novinky.to_param, :novinky => { "title" => "invalid value" }}, valid_session
        assigns(:novinky).should eq(novinky)
      end

      it "re-renders the 'edit' template" do
        novinky = Novinky.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Novinky.any_instance.stub(:save).and_return(false)
        put :update, {:id => novinky.to_param, :novinky => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested novinky" do
      novinky = Novinky.create! valid_attributes
      expect {
        delete :destroy, {:id => novinky.to_param}, valid_session
      }.to change(Novinky, :count).by(-1)
    end

    it "redirects to the novinkies list" do
      novinky = Novinky.create! valid_attributes
      delete :destroy, {:id => novinky.to_param}, valid_session
      response.should redirect_to(novinkies_url)
    end
  end

end
